spring.application.name=api-gateway

server.port=8080

# Localizador de servicios dinámico a través de Eureka (Creación automatica de rutas)
spring.cloud.gateway.discovery.locator.enabled=true
# mapear los nombres en minúscula en la URL
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ROUTE 1: Product Service
spring.cloud.gateway.routes[0].id=product-service-route
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**

# ROUTE 2: Inventory Service
spring.cloud.gateway.routes[1].id=inventory-service-route
spring.cloud.gateway.routes[1].uri=lb://inventory-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/inventory/**

# EUREKA CLIENT CONFIGURATION
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
